---
deployment:
  tasks:
    - export DEPLOYPATH=/home/<your-cPanel-user>/public_html/recruitiq.automatedconetruck.com.au/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R modules $DEPLOYPATH